env:
  es2022: true
  node: true
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 2022
  sourceType: module
plugins:
  - '@typescript-eslint'
rules:
  '@typescript-eslint/member-delimiter-style':
    - error
  '@typescript-eslint/no-unused-vars':
    - off
  '@typescript-eslint/no-explicit-any':
    - off
