.git
.gitkeep
.gitattributes
.gitignore

.editorconfig

Makefile
ci/*.dockerignore
ci/*.gvy
ci/*.Dockerfile
ci/Dockerfile
Jenkinsfile.gvy


## CI
log/
lint/
build/
dist/
node_modules/

dist/.build

coverage/b
.nyc_output/

resources/

*.tgz


## IDE
*.code-workspace
.vscode/
.idea/


## OS
.DS_Store
