.git
.gitkeep
.gitattributes
.gitignore

.editorconfig

Makefile
ci/
Jenkinsfile.gvy


## CI
log/
lint/
build/
dist/
node_modules/

dist/.build

coverage/
.nyc_output/

resources/

*.tgz


## IDE
*.code-workspace
.vscode/
.idea/


## OS
.DS_Store
