import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
    changes: [
        {
            type: 'autogenerated',
            dirName: '.'
        }
    ]
};

export default sidebars;
